---
kind: pipeline
type: docker
name: gerror

platform:
  os: linux
  arch: amd64

steps:
  - name: "test"
    image: golang:1.19
    commands:
      - go test ./...
---
kind: signature
hmac: 36786793fd121054c9cadf81a86522a023d4619fae879ee875c98d702c818424

...
